### ISSUE TITLE
关于xch离线地址的问题

### ISSUE THREAD

**Issue by ruiyeclub** [mengyaoyu/bech32m-chia#1]
想请问一下 怎么生成puzzleHash的呢 已经拿到了私钥和公钥

**Comment by markybc** [comment]
通过chia-network官网里面的api获取到address，然后通过AddressUtils里面的getPuzzleHash(address)方法获取puzzleHash

**Comment by ruiyeclub** [comment]
这个我知道 我现在想离线生成xch地址 助剂词到种子到私钥公钥那种 现在已经拿到了公私钥 不知道怎么生成puzzleHash

**Comment by markybc** [comment]
生成xch地址的方法我没研究，不过你可以让你的chia钱包不联网调用官网的API获取地址

**Comment by ruiyeclub** [comment]
好的
